### ISSUE TITLE
Containerize this

### ISSUE THREAD

**Issue by calcharp** [Imageomics/TraitBlender#1]

**Comment by calcharp** [comment]
The python script that generates datasets can now run from the command line, so it can be dockerized like I want. The bash script shows an example. It takes the path the the .json file, the python file with the mesh generating function, and the path the the .csv file with the tabular trait data as arguments.

**Comment by johnbradley** [comment]
I'm getting the following error when running the script:
```
Error: Python: Traceback (most recent call last):
  File "/src/TraitBlender/generate_dataset.py", line 56, in <module>
    scene.make_mesh_function_path = make_mesh_function_path
AttributeError: 'Scene' object has no attribute 'make_mesh_function_path'
```
This is with Blender 3.6.2 on Linux.

**Comment by johnbradley** [comment]
I added `bpy.ops.preferences.addon_enable(module="TraitBlender")` to the top of generate_dataset.py and it started working.

**Comment by johnbradley** [comment]
Example image named `the first snail_Front.png` from output directory.
![the first snail_Front](https://github.com/calcharp/TraitBlender/assets/1024463/0b6a65a6-0dcb-4aca-9536-37956ad0a82a)

**Comment by calcharp** [comment]
Great! Thanks. I had to make some changes to the loop script as well, some some was breaking. It was updated on the main branch, if we could merge to the docker branch and then back to main or something

**Comment by johnbradley** [comment]
@calcharp I'll merge the latest changes from main into the docker branch. My usual process is to work on a branch while I work out the changes. Then I will create a PR to merge the changes into the main branch and add you as the reviewer. That way you only need to look over the changes once.
